### PR TITLE
Add `==` exception for `null` and `undefined`

### PR DESCRIPTION
**Pull request by dwick**
see: `jshint eqnull: true` for more info.

:eyeglasses: @ajacksified @madbook @umbrae

### CODE REVIEW

**Comment by ajacksified** [comment]
Seems reasonable to me. :fish:

**Comment by madbook** [comment]
:nail_care: I'd really like it in these cases if a comment was attached to show that its an intentional usage of the shortcut.  99% of the time I'm going to assume that this was an accident.

**Comment by dwick** [comment]
that's sort of the point of jshint (and actually enforcing the errors)

**Comment by madbook** [comment]
jshint can't distinguish between `foo == null` being an accidental vs an intentional usage of this shortcut

**Comment by dwick** [comment]
i think making a distinction between `null` and `undefined` is more dangerous honestly

**Comment by madbook** [comment]
there is a distinction though; `null` is an explicitly set value representing nothing, and `undefined` is non-existent value/property.

although, now that I think about it, adding a comment to note this is more verbose than just doing:

```
if (x === null || x === undefined) { ... }
```

so i'd really really just prefer that we don't use the shortcut at all :P

**Comment by umbrae** [comment]
I don't feel strongly about this but I think @madbook makes a good argument for why to not have it. I'm mildly -1 on it.

**Comment by umbrae** [comment]
:nail_care: to clean up my harold

**Comment by ajacksified** [comment]
Going to close this, re-open if you feel super strongly about it.

**Pull request closed without merging**
