### PR TITLE
Add initial puppet style guide.

### PR DESCRIPTION
**Pull request by spladug**
:eyeglasses: @rram @jdubs @kjoconnor

### CODE REVIEW

**Comment by kjoconnor** [comment]
I kind of like the puppet rules about quoting, since it makes you certain that you're meaning to use variables or not in your strings, but I don't care that much.

**Comment by spladug** [comment]
I tend to agree, myself, about the quotes.  Just was including that from discussion in slack last night.

**Comment by rram** [comment]
:fish:

**Comment by spladug** [comment]
I removed the special case about quotes because I think we should just stick with that. Any objections?

:haircut:

**Comment by kjoconnor** [comment]
Nope, looks good! :fish:

**Comment by spladug** [comment]
a10817b2e077a7a6b8d9910a5bb7434f8fc9889b

**Pull request closed without merging**
